[project]
name = "lambda"
version = "0.1.0"
description = "AWS Lambda function for GitHub App webhooks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-lambda-powertools>=3.19.0",
    "pygithub>=2.7.0",
]
